# Generated by Django 5.1.6 on 2025-02-27 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_fornecedor_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome do produto')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Produtos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('quantidadeEstoque', models.PositiveBigIntegerField(default=0, verbose_name='Quantidade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.fornecedor')),
            ],
        ),
    ]
